alias: üîê RFID - Activer / D√©sactiver Alarme
description: Active ou d√©sactive l‚Äôalarme lors du passage du badge RFID

trigger:
  - platform: state
    entity_id: binary_sensor.badge_alarme
    to: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.alarme_maison
            state: disarmed
        sequence:
          - service: alarm_control_panel.alarm_arm_away
            target:
              entity_id: alarm_control_panel.alarme_maison
            data:
              code: "0000"
      - default:
          - service: alarm_control_panel.alarm_disarm
            target:
              entity_id: alarm_control_panel.alarme_maison
            data:
              code: "0000"

mode: single

