esphome:
  name: lecteur-rfid
  friendly_name: Lecteur RFID Alarme

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: true

pn532:
  id: pn532_reader
  update_interval: 500ms

binary_sensor:
  - platform: pn532
    uid: "EB-36-1F-31"   # Ã€ remplacer par ton UID
    name: "Badge Alarme"

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: GPIO2
    num_leds: 1
    name: "LED Lecteur RFID"
    id: led_rfid

switch:
  - platform: gpio
    pin: GPIO7
    name: "Buzzer RFID"
    id: buzzer

on_boot:
  then:
    - light.turn_on:
        id: led_rfid
        red: 0%
        green: 0%
        blue: 40%

